[package]
name = "magisk"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
cxx-gen = { path = "../external/cxx-rs/gen/lib" }

[dependencies]
base = { path = "../base" }
cxx = { path = "../external/cxx-rs" }
num-traits = "0.2"
num-derive = "0.3"
