[package]
name = "base"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[build-dependencies]
cxx-gen = { path = "../external/cxx-rs/gen/lib" }

[dependencies]
cxx = { path = "../external/cxx-rs" }
libc = "0.2"
cfg-if = "1.0"
