[package]
name = "magiskinit"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
cxx-gen = { path = "../external/cxx-rs/gen/lib" }

[dependencies]
base = { path = "../base" }
cxx = "1.0.69"
